"""create services table

Revision ID: 923d2d7bcf0c
Revises: f07b673d668a
Create Date: 2025-09-27 11:48:54.010308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '923d2d7bcf0c'
down_revision: Union[str, Sequence[str], None] = 'f07b673d668a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('appointments_provider_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_client_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['client_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'users', ['provider_id'], ['id'])
    op.drop_column('appointments', 'created_at')
    op.create_index(op.f('ix_availability_id'), 'availability', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_availability_id'), table_name='availability')
    op.add_column('appointments', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_client_id_fkey'), 'appointments', 'users', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('appointments_provider_id_fkey'), 'appointments', 'users', ['provider_id'], ['id'], ondelete='CASCADE')
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('appointments', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
