"""add service_id to appointments

Revision ID: f00e5cc0bb19
Revises: 247b81331e27
Create Date: 2025-09-27 13:18:23.801641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00e5cc0bb19'
down_revision: Union[str, Sequence[str], None] = '247b81331e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('service_id', sa.Integer(), nullable=True))
    op.alter_column('appointments', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('appointments_client_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_provider_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'users', ['provider_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_provider_id_fkey'), 'appointments', 'users', ['provider_id'], ['id'])
    op.create_foreign_key(op.f('appointments_client_id_fkey'), 'appointments', 'users', ['client_id'], ['id'])
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('appointments', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'service_id')
    # ### end Alembic commands ###
