"""switch availability to exact dates

Revision ID: f07b673d668a
Revises: f882029aaab1
Create Date: 2025-09-24 21:46:17.860247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07b673d668a'
down_revision: Union[str, Sequence[str], None] = 'f882029aaab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "availability",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("provider_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE")),
        sa.Column("date", sa.Date, nullable=False),
        sa.Column("start_time", sa.Time, nullable=False),
        sa.Column("end_time", sa.Time, nullable=False),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability', sa.Column('weekday', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('availability', 'date')
    # ### end Alembic commands ###
